<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="FB_MatrixElementSum_Test" Id="{4dcbf96e-83e7-0942-1466-313401dfc7f7}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_MatrixElementSum_Test EXTENDS FB_TestSuite
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[WhenDifferentExpectError();
WhenmatchingExpectResult();]]></ST>
    </Implementation>
    <Method Name="WhenDifferentExpectError" Id="{7c8500e5-8b06-049b-26ef-8c68b2165305}">
      <Declaration><![CDATA[METHOD PRIVATE WhenDifferentExpectError
VAR_INPUT
END_VAR
VAR
	M1 : Matrix;
	M2 : Matrix;
	M3 : Matrix;
	Result : BOOL;
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[TEST('WhenDifferentExpectError');

// @TEST-RUN
M1.InitMagicSquare(3);
M2.InitMagicSquare(5);
Result := M3.AsElementSum(M1,M2);

// @TEST-ASSERT
AssertFalse(Result,'Main function call was unexpectedly successful');

TEST_FINISHED();]]></ST>
      </Implementation>
    </Method>
    <Method Name="WhenMatchingExpectResult" Id="{4704fc92-c368-0aa0-2102-7dfaed302d6f}">
      <Declaration><![CDATA[METHOD PRIVATE WhenMatchingExpectResult
VAR_INPUT
END_VAR
VAR
	M1 : Matrix;
	M2 : Matrix;
	M3 : Matrix;
	Result : BOOL;
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[TEST('WhenShrunkExpectDataRetained');

// @TEST-RUN
M1.InitMagicSquare(3);
M2.InitMagicSquare(3);
Result := M3.AsElementSum(M1,M2);
M1.Scale(2);

// @TEST-ASSERT
AssertTrue(Result,'Main function call was not successful');
AssertTrue(M3.IsEqual(M1),'Data was successfully added');

TEST_FINISHED();]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_MatrixElementSum_Test">
      <LineId Id="39" Count="0" />
      <LineId Id="29" Count="0" />
    </LineIds>
    <LineIds Name="FB_MatrixElementSum_Test.WhenDifferentExpectError">
      <LineId Id="5" Count="0" />
      <LineId Id="15" Count="0" />
      <LineId Id="10" Count="0" />
      <LineId Id="25" Count="0" />
      <LineId Id="27" Count="0" />
      <LineId Id="9" Count="0" />
      <LineId Id="16" Count="0" />
      <LineId Id="7" Count="0" />
      <LineId Id="17" Count="0" />
      <LineId Id="8" Count="0" />
      <LineId Id="6" Count="0" />
    </LineIds>
    <LineIds Name="FB_MatrixElementSum_Test.WhenMatchingExpectResult">
      <LineId Id="5" Count="0" />
      <LineId Id="15" Count="0" />
      <LineId Id="10" Count="0" />
      <LineId Id="43" Count="1" />
      <LineId Id="36" Count="0" />
      <LineId Id="46" Count="0" />
      <LineId Id="16" Count="0" />
      <LineId Id="7" Count="0" />
      <LineId Id="17" Count="0" />
      <LineId Id="37" Count="0" />
      <LineId Id="8" Count="0" />
      <LineId Id="6" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>