<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="PRG_TEST" Id="{5f2716c6-31ed-49cd-815d-6106c2eebb72}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PRG_TEST
VAR
	fbDynamicMatrix : FB_DynamicMatrix_Test;
	fbArray: FB_Array_Test;
	fbMatrixGetMagicSquare : FB_MatrixGetMagicSquare_Test;
	fbMatrixSubmatrix : FB_MatrixSubMatrix_Test;
	fbMatrixGrow : FB_MatrixGrow_Test;
	fbMatrixShrink : FB_MatrixShrink_Test;
	fbMatrixElementSum : FB_MatrixElementSum_Test;
	fbMatrixElementProduct : FB_MatrixElementProduct_Test;
	fbMatrixDeterminate : FB_MatrixDeterminate_Test;
	fbMatrixMatrixProduct : FB_MatrixMatrixProduct_Test;
	fbVectorCrossProdcut : FB_VectorCrossProduct_Test;
	fbStaticMatrix : FB_StaticMatrix_Test;
	fbMatrixTranspose : FB_MatrixTranspose_Test;
	fbMatrixInvert : FB_MatrixInvert_Test;
	fbCsvReadWrite : FB_CsvReadWrite_Test;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[TcUnit.RUN();]]></ST>
    </Implementation>
    <LineIds Name="PRG_TEST">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>